-- ESTA DECLARACION CREA UNA TABLA
CREATE TABLE tbl_Paciente(
	-- DATOS QUE POSEE LA TABLA
	PacienteID INT NOT NULL IDENTITY(1, 1),
	Nombre VARCHAR(50) NOT NULL,
	Apellido VARCHAR(50) NULL,
	Direccion VARCHAR(100) NULL,
	Email VARCHAR(100) NULL,

	-- DEFINE LA PRIMARY KEY DE LA TABLA
	CONSTRAINT PK_Paciente PRIMARY KEY(PacienteID)
)
