-- ESTA DECLARACION CREA UNA TABLA
CREATE TABLE tbl_Historia(
	-- DATOS QUE POSEE LA TABLA
	HistoriaID INT NOT NULL IDENTITY(1, 1),
	Fecha_De_Historia DATETIME NULL,
	observacion VARCHAR(2000) NULL,

	-- DEFINE LA PRIMARY KEY DE LA TABLA
	CONSTRAINT PK_Historia PRIMARY KEY(HistoriaID)
)