CREATE TABLE tbl_Turno(
	-- DATOS QUE POSEE LA TABLA
	TurnoID INT NOT NULL IDENTITY(1, 1),
	FechaHoraTurno DATETIME NULL,
	EstadoTurno SMALLINT NULL,
	Observacion VARCHAR(2000) NULL,

	-- DEFINE LA PRIMARY KEY DE LA TABLA
	CONSTRAINT PK_Turno PRIMARY KEY(TurnoID)
)