CREATE TABLE tbl_Pago(
	PagoID INT NOT NULL IDENTITY(1, 1),
	Concepto TINYINT NOT NULL,
	Fecha DATETIME NOT NULL,
	Monto MONEY NOT NULL,
	Estado TINYINT NULL,
	Observacion VARCHAR(1000) NULL

	CONSTRAINT PK_Pago PRIMARY KEY(PagoID)
)